version: "3"

services:
  postsql:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - postgres
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "4000:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=ledungcobra@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=ledungcobra
    networks:
      - postgres
networks:
  postgres: 
    driver: bridge
